"""
content/ — every piece of copy the app ships with, that isn't
generated by Gemini.

Nothing here decides *what happens* (that's core.prompt_selector).
This package only supplies words: loading-sequence flavor text,
comedic failure copy, ending headlines, few-shot JSON examples for
Gemini to imitate, emergency insights, and footer slogans.

core/ already knows how to use these — errors.py, fallback.py, and
prompts.py each try to import the matching file here and quietly fall
back to a small inline default if it's missing. Nothing needed to
change in core/ to wire this package in; it was built to expect it.
"""
